# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Irene Feliciotti
tagline:          'A crazy neuroscientist!'
description:      'Irene be crazy'
url:              https://iref-2310.github.io/
baseurl:          /

author:
  name:           'Irene Feliciotti'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
